### PR TITLE
Ignore new qmake generated files.

### PR DESCRIPTION
**Pull request by jeandudey**

### CODE REVIEW

**Comment by lolzballs** [comment]
Qmake doesn't like build directories underneath the source directory. I don't think this is that useful.

**Comment by Jtramey** [comment]
I agree, All of my release and debug builds are saved to the same folder as
folder
 the actual source.

**Comment by jeandudey** [comment]
I'm not compiling underneath the source directory, qmake generates these new files:

```
object_script.ProjectAscension.Debug
object_script.ProjectAscension.Release
```

So i added to .gitignore the patterns `*.*.Debug` `*.*.Release` to ignore these files.

Note: I'm building from the command line not from QtCreator.

**Comment by Hal9007** [comment]
Hey jeandudey, we'll merge these changes because they are nominal, but please reattempt your build on the current master branch. If the generated files persist, open a new issue and we'll go from there.

**Pull request merged**
