### PR TITLE
Revert the pointer fixes

### PR DESCRIPTION
**Pull request by elken**
It was just a small hack to check if a game exists. The db class needs some form of checking if the game exists, for Steam it might be an idea to add a 3rd party ID field, or just have a function verifying the query returns success.

### CODE REVIEW

**Comment by lolzballs** [comment]
We could return a tuple with a boolean and the Game, with the boolean being success.

Another thing you might want to throw in that pr is getting rid of the typedef on the Game struct in Database.h. I was stuck in C-land while I was making that.

**Comment by elken** [comment]
I forget about tuples so often... That's a pretty sane solution.

Ok sure, added.

**Comment by elken** [comment]
Second opinion RE: this, would you prefer isExists to take 2 arguments, id & name, and pass NULL if one isn't needed, or overload isExists?

Also do you think we need a getGameByPath function? I can't think of an edge case for it, but it might be useful somewhere.

And I've changed the other getGame functions to use this, should error-handling be part of getGame, or do you think the implementation of getGame should handle errors?

**Comment by lolzballs** [comment]
isExists doesn't sound right, try isExistant. One thing for it though, it will be slower than having the getGame\* functions return a tuple with a boolean, because you will have to query the database twice.

A getGameByPath may be useful, create it if you want.

As for the error handling, I'm not sure. Letting the function that uses getGame\* would allow for more freedom in how to handle errors, based on the context in which the error occurred.

**Comment by elken** [comment]
Yeah, good point.

It's only returning the Game, isExists returns a blank game if nothing's found. 

Ok, thought so. :)

**Pull request merged**
