### PR TITLE
Fix bug when Steam is not installed on Windows

### PR DESCRIPTION
**Pull request by lolzballs**
The QSettings query would return an empty string which, when put into QDir, would return the current directory. Because the current directory exists, it passes through the steamRoot.exists() check.

To fix this I just check if the QSettings query returned an empty string.

### CODE REVIEW

**Comment by elken** [comment]
Oops, yeah I haven't got my Windows testing infrastructure setup yet.

**Comment by lolzballs** [comment]
Don't worry about it, because I primarily use Linux. @Hal9007 uses Windows but _probably_ has Steam installed on his computer so it was hard to find.

**Comment by elken** [comment]
Yeah me too :) I figured using the registry was the most portable way in
case someone installed it to something dumb like
C:\Users\Username.long-dumb-folder\memes\

**Comment by lolzballs** [comment]
Whoops, didn't mean to add that to this :/

**Comment by lolzballs** [comment]
I force pushed. Sorry if your stuff messes up.

**Comment by elken** [comment]
The merge is empty, everything's gravy :)

**Pull request merged**
