### PR TITLE
Windows and Unix Main Panels

### PR DESCRIPTION
**Pull request by lolzballs**
This change makes WinPanel and UnixPanel use a similar structure to display a window. The window then gets a MainPanel added to it.

The MainPanel has the common things between Windows and Unix, and the WinMainPanel + UnixMainPanels extend the MainPanel to provide platform specific stuff.

### CODE REVIEW

**Comment by lolzballs** [comment]
This hasn't been tested on Windows yet.

**Comment by lolzballs** [comment]
Ok. This is working on Linux and Windows.

**Comment by lolzballs** [comment]
I seem to have screwed up the window dragging on linux.

**Comment by lolzballs** [comment]
Ok, unix dragging is fixed. If someone wants to test this out before I merge, that would be great!

**Comment by Hal9007** [comment]
Branch appears to be working on both Windows and Linux. Merged.

**Comment by yrrah2** [comment]
Have you tried different DE/WMs?

**Comment by lolzballs** [comment]
@yrrah2 I've only currently tried Unity, I'll get someone to test xfce4 soon

**Comment by Hal9007** [comment]
@yrrah2 My attempt was on XFCE Debian, worked just fine.

**Comment by yrrah2** [comment]
I will try some others when I get home as I am running i3/GNOME

**Pull request merged**
