### PR TITLE
Steam find

### PR DESCRIPTION
**Pull request by elken**
Issue with *source games, tested with ~10 or so games.

Working on win8.1, Arch Linux & Debian Testing.

RE: the icu*dll changes, Qt 5.5 ships with 54, so some I tried hacking together an `if (EXISTS)`.

### CODE REVIEW

**Comment by lolzballs** [comment]
Travis fails because the travis on master branch is still using the old qmake system. The dev branch is using cmake, but we are having some issues with apt-get not working.

**Comment by elken** [comment]
Ah, I was about to comment, I though it was me. The boost stuff is fuuuun on Windows.

Anything I can do to help?

**Comment by lolzballs** [comment]
For now, just change this pull request to merge into the dev branch and play around with the .travis.yml if you want to. I'll also be playing around with travis.

**Comment by elken** [comment]
Ah my bad, didn't see there was a dev branch.

**Comment by elken** [comment]
Managed to get cmake working, trying to find a backport of Qt5 seems futile, apparently [SemaphoreCI](https://semaphoreci.com/) uses a more recent version of Ubuntu. I'll look at builds over there.

**Comment by lolzballs** [comment]
We already got backports of Qt5, and I got a ppa for cmake. However the ppa doesn't like to work. :/

**Comment by elken** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

No because the backport of cmake needs a backported version of
cmake-data because Ubuntu. And the backport of Qt5 doesn't have Qtgui
according to the page. I'll do another build and test.

On 04/07/15 20:15, Benjamin Cheng wrote:

> We already got backports of Qt5, and I got a ppa for cmake. However
> the ppa doesn't like to work. :/
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/Proj-Ascension/Client/pull/33#issuecomment-1185435
> 60>.
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2

iQIcBAEBCAAGBQJVmDFAAAoJEGNtxknsiBy2LRQP/2zFc+epwLxaT0VM29VyF7TV
lDRiRiqlGzj5S3IkhglI0fR3+UjQ8LAFPFLh4I9vh95DoVEDES/jW5da9UjLFAq5
zgVUeoqHVvPi6u3y3DUVRL+DvRkXjamxvWkEAREETUVZHIle0VEWbsdbemg8hkbQ
bej5zC4/F338+EivPIZvAcyxI+uACG2vZOwtoiMHHtxbshpJCKmlyxtvdHfHMX6Q
VCZ0H79FQzVZgPDI3pXPSap3ysxJyVSrSG3Ysl8mH3IYrK9lS7UJYrvTS9QkB/sh
eV1mhchjbNgpYH8JjfbUuTOHRwmNJGSEHHV1R86gaNuhB8I1axqYP0+1RVsWRMGf
LaBKWfb8QFEaYMVvwD+eOuDD5ky80VJ03J1QAyI5Gj+0zGJf3lqVmfQC3C+hOlK7
0/0nv73iQ3Xsl7LloNZ3KLXXyFDqxZA9X+qBnp1JPFgYk7a22pufkBSoHDji5PZ0
cJtR6iMDbQVOBI1s0twr8IfW71pw/41Gldq3IgFOYTZtThk3MCR/4Kt/WW/tKk9l
+hXcfJ6hbFEyEWy2TobHHeCyUuYnnfAFkPpOq65oKmO5rzlLqZ6UuMSeZTCgPE5k
UI3p8+AL4y36yoErKp7KrFR59KiJ9WM7ao7uWHhMMMtmK6Q127XObkwinyhvFIbf
Tz85IX+gZ5m9ilrowqzS
=XxtC
-----END PGP SIGNATURE-----

**Comment by lolzballs** [comment]
> the backport of cmake needs a backported version of cmake-data

It does have that:
image

That from the details of the packages in [this ppa](https://launchpad.net/~sschuberth/+archive/ubuntu/cmake-here/+packages)

**Comment by elken** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Yup, semaphore uses Ubuntu 14.04, has gh integration & you can SSH
into the instances.

On 04/07/15 20:15, Benjamin Cheng wrote:

> We already got backports of Qt5, and I got a ppa for cmake. However
> the ppa doesn't like to work. :/
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/Proj-Ascension/Client/pull/33#issuecomment-1185435
> 60>.
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2

iQIcBAEBCAAGBQJVmDI6AAoJEGNtxknsiBy25nIP/i3YY//aA3dYVNSQhofuhiaO
UF8G+IbperRga+AAoJxfqiy4VI4AdzAVeWHSYzb/lozLBHBP+KX7x0HaqHqFYlQE
gbjMNljxRyvF3J7Wmgx8FwbQ+7emLQNZjuaxToq/1/fsVxw/yhWFuq/AYzyN4whR
9Pd8OYEvWTrqLp5llUqgeycp+RKbgRz8FG+RGm8IhXl2PEp7gWUpM+/1Hh7Vz/la
aCrI9FDpEI1SynwHOeZL6agFtw4tsBNcW+DN82zhn011gsZnede34caIy9Yf86EV
ph8oANi/Gk2TqY1QD4nqBmE46rLDJ+zVEwpVT1UmA9wDPL8xesW/5Y/PCgtpkxf+
WXKWo5pCsOIF24AC2xoIU1eqWBEw9pRliZd8M9zOOJhmCz6KgTutN7jCPnkSzITB
LVoMD9CDzWR86l8mRvJwq0Lc/fY9hTnpeVcVifAc9NQvdoaeLTJh61xza07uu0tf
z8lO/q/0p0kMyJLCY9tOeTbuenynFwhgL0crq/Un4ksBYaQHT0kWDeKi1ktg7a76
Us8XCGN22EUTbZ3fZklwJdftw5Oj8FwL2QDHfXE2izr+fkZYZN/Z9Zot4aqCIaM3
xU7RmeVoQ0Co5w3ftgV/ELAmJCmQfYSZZRmbtxqvRRH2UxBgVXfsfv8MzTVNfon7
+Bcwp5rc96To7BARtA1u
=Hbdr
-----END PGP SIGNATURE-----

**Comment by elken** [comment]
I just built it from source & it works fine. Just needs to find Qtgui.

[My build](https://travis-ci.org/elken/Client)

**Comment by lolzballs** [comment]
libqt5gui5-dev isn't a package... even on 15.04
image

You shouldn't really need any qt package other than the ones in the current travis.yml, qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev.

**Comment by elken** [comment]
It shouldn't, but it can't find [QMessageBox](https://s3.amazonaws.com/archive.travis-ci.org/jobs/69562263/log.txt)

**Comment by elken** [comment]
Appending the specific version number to cmake fixes the cmake issue. [(diff)](http://sprunge.us/giPL)

**Comment by lolzballs** [comment]
Wow, I wasn't even thinking in that direction. Thanks, I'll try it out!

**Comment by elken** [comment]
I didn't even know it was a thing, I knew apt-get supported `-t` for choosing a specific repo, but PPAs don't count as normal repos.

**Comment by lolzballs** [comment]
Seems like you're right about the QMessageBox thing, I'm going to boot up a vm and see exactly what is needed.

**Comment by elken** [comment]
Well on my builds, the library is _definately_ [there](http://i.imgur.com/YF0RJNl.png). CMake just spits that out, and apparently its a bug that should have been [fixed](http://www.cmake.org/pipermail/cmake/2014-November/059193.html).

EDIT: Amending with sed suppresses the errors, but still no luck finding qtlibs.

**Comment by lolzballs** [comment]
The CMake issue seems to only appear in 3.2.3, tried it with 3.2.2 on 15.04 and it was fine.

**Comment by elken** [comment]
I'll try building 3.2.2 from source then.

**Comment by lolzballs** [comment]
I take that back, we seem to be missing the QtWidgets library. `locate QMessageBox` gives me /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMessageBox on my main machine, however it doesn't exist on the virtual machine I spun up.

**Comment by elken** [comment]
Yeah I manually added the dirs using a foreach and it finds everything except QSqlDatabase for some reason.

**Comment by lolzballs** [comment]
I lied again :P.

`find / -type f -name "QMessageBox"` gives `/usr/include/qt5/QtWidgets/QMessageBox`
and similarily QSqlDatabase is found too.

**Comment by elken** [comment]
Yeah the libraries are all there, even QSqlDatabase, CMake's just deciding to have a blind spot with it xD

**Comment by lolzballs** [comment]
THERE WE GO!

We probably need to specify QtWidgets and stuff in the include_directories of CMake.

**Comment by elken** [comment]
Already said I've done that :p [CMakeLists diff](http://sprunge.us/hXFS)

**Comment by lolzballs** [comment]
Ahh, should probably pay more attention.

You probably need to add `Qt5Sql_INCLUDE_DIRS` to it then, if the other stuff worked.

**Comment by elken** [comment]
Yeah, I just spotted that -_-

It's late, leave me alone :p

**Comment by lolzballs** [comment]
Don't worry, I should have spotted this wayyy earlier...

Also, `${Qt5WebKiit_INCLUDE_DIRS}` has a typo.

**Comment by elken** [comment]
Arses, I wish cmake had a decent linter so I didn't have validate this xD

**Comment by elken** [comment]
IT BUILDS!

I've never been this happy. :+1: 

[Here](http://sprunge.us/VNMQ) is a full diff of the changes.
[Build Status](https://travis-ci.org/elken/Client)

**Pull request closed without merging**
